export const FETCH_TOKEN = 'FETCH_TOKEN';
export const FETCH_TOKEN_SUCCESS = 'FETCH_TOKEN_SUCCESS';
export const FETCH_TOKEN_FAIL = 'FETCH_TOKEN_FAIL';

export const FETCH_SESSION_ID = 'FETCH_SESSION_ID';
export const FETCH_SESSION_ID_SUCCESS = 'FETCH_SESSION_ID_SUCCESS';
export const FETCH_SESSION_ID_FAIL = 'FETCH_SESSION_ID_FAIL'; 

export const LOGOUT = 'LOGOUT';

export const FETCH_ACCOUNT_DETAILS = 'FETCH_ACCOUNT_DETAILS';
export const FETCH_ACCOUNT_DETAILS_SUCCESS = 'FETCH_ACCOUNT_DETAILS_SUCCESS';
export const FETCH_ACCOUNT_DETAILS_FAIL = 'FETCH_ACCOUNT_DETAILS_FAIL';

