export const FETCH_TOKEN = 'FETCH_TOKEN';
export const FETCH_TOKEN_SUCCESS = 'FETCH_TOKEN_SUCCESS';
export const FETCH_TOKEN_FAIL = 'FETCH_TOKEN_FAIL';

export const FETCH_SESSION_ID = 'FETCH_SESSION_ID';
export const FETCH_SESSION_ID_SUCCESS = 'FETCH_SESSION_ID_SUCCESS';
export const FETCH_SESSION_ID_FAIL = 'FETCH_SESSION_ID_FAIL'; 

export const FETCH_GUEST_SESSION_ID = 'FETCH_GUEST_SESSION_ID';
export const FETCH_GUEST_SESSION_ID_SUCCESS = 'FETCH_GUEST_SESSION_ID_SUCCESS';
export const FETCH_GUEST_SESSION_ID_FAIL = 'FETCH_GUEST_SESSION_ID_FAIL';

export const LOGOUT = 'LOGOUT';

export const FETCH_ACCOUNT_DETAILS = 'FETCH_ACCOUNT_DETAILS';
export const FETCH_ACCOUNT_DETAILS_SUCCESS = 'FETCH_ACCOUNT_DETAILS_SUCCESS';
export const FETCH_ACCOUNT_DETAILS_FAIL = 'FETCH_ACCOUNT_DETAILS_FAIL';

export const FETCH_MEDIA_STATE = 'FETCH_MEDIA_STATE';
export const FETCH_MEDIA_STATE_SUCCESS = 'FETCH_MEDIA_STATE_SUCCESS';
export const FETCH_MEDIA_STATE_FAIL = 'FETCH_MEDIA_STATE_FAIL';

export const UPDATE_MEDIA_STATE = "UPDATE_MEDIA_STATE";
export const UPDATE_MEDIA_STATE_SUCCESS = "UPDATE_MEDIA_STATE_SUCCESS";
export const UPDATE_MEDIA_STATE_FAIL = "UPDATE_MEDIA_STATE_FAIL";

export const FETCH_ACCOUNT_LISTS = 'FETCH_ACCOUNT_LISTS';
export const FETCH_ACCOUNT_LISTS_SUCCESS = 'FETCH_ACCOUNT_LISTS_SUCCESS';
export const FETCH_ACCOUNT_LISTS_FAIL = 'FETCH_ACCOUNT_LISTS_FAIL';

export const CLEAR_LIST = 'CLEAR_LIST';
export const CLEAR_LIST_SUCCESS = 'CLEAR_LIST_SUCCESS';
export const CLEAR_LIST_FAIL = 'CLEAR_LIST_FAIL';

export const DELETE_LIST = 'DELETE_LIST'; 
export const DELETE_LIST_SUCCESS = 'DELETE_LIST_SUCCESS'; 
export const DELETE_LIST_FAIL = 'DELETE_LIST_FAIL';

export const CREATE_NEW_LIST = 'CREATE_NEW_LIST';
export const CREATE_NEW_LIST_SUCCESS = 'CREATE_NEW_LIST_SUCCESS';
export const CREATE_NEW_LIST_FAIL = 'CREATE_NEW_LIST_FAIL';

export const FETCH_MEDIA = 'FETCH_MEDIA';
export const FETCH_MEDIA_SUCCESS = 'FETCH_MEDIA_SUCCESS';
export const FETCH_MEDIA_FAIL = 'FETCH_MEDIA_FAIL';

export const ADD_MEDIA = 'ADD_MEDIA'; 
export const REMOVE_MEDIA = 'REMOVE_MEDIA';
export const ADD_RATING = 'ADD_RATING';
export const REMOVE_RATING = 'REMOVE_RATING';  

export const START = 'START';
export const FAIL = 'FAIL'; 

export const SET_GUEST_MEDIA = 'SET_GUEST_MEDIA';

export const ADD_STATE_MEDIA = 'ADD_STATE_MEDIA';
export const REMOVE_STATE_MEDIA = 'REMOVE_STATE_MEDIA'; 
