export const FETCH_TOKEN = 'FETCH_TOKEN';
export const FETCH_TOKEN_SUCCESS = 'FETCH_TOKEN_SUCCESS';
export const FETCH_TOKEN_FAIL = 'FETCH_TOKEN_FAIL';

export const FETCH_SESSION_ID = 'FETCH_SESSION_ID';
export const FETCH_SESSION_ID_SUCCESS = 'FETCH_SESSION_ID_SUCCESS';
export const FETCH_SESSION_ID_FAIL = 'FETCH_SESSION_ID_FAIL'; 

export const LOGOUT = 'LOGOUT';

export const FETCH_ACCOUNT_DETAILS = 'FETCH_ACCOUNT_DETAILS';
export const FETCH_ACCOUNT_DETAILS_SUCCESS = 'FETCH_ACCOUNT_DETAILS_SUCCESS';
export const FETCH_ACCOUNT_DETAILS_FAIL = 'FETCH_ACCOUNT_DETAILS_FAIL';

export const FETCH_MEDIA_STATE = 'FETCH_MEDIA_STATE';
export const FETCH_MEDIA_STATE_SUCCESS = 'FETCH_MEDIA_STATE_SUCCESS';
export const FETCH_MEDIA_STATE_FAIL = 'FETCH_MEDIA_STATE_FAIL';

export const UPDATE_MEDIA_STATE = "UPDATE_MEDIA_STATE";
export const UPDATE_MEDIA_STATE_SUCCESS = "UPDATE_MEDIA_STATE_SUCCESS";
export const UPDATE_MEDIA_STATE_FAIL = "UPDATE_MEDIA_STATE_FAIL";

export const RATE_MEDIA = "RATE_MEDIA";
export const RATE_MEDIA_SUCCESS = "RATE_MEDIA_SUCCESS";
export const RATE_MEDIA_FAIL = "RATE_MEDIA_FAIL";

export const FETCH_ACCOUNT_LISTS = 'FETCH_ACCOUNT_LISTS';
export const FETCH_ACCOUNT_LISTS_SUCCESS = 'FETCH_ACCOUNT_LISTS_SUCCESS';
export const FETCH_ACCOUNT_LISTS_FAIL = 'FETCH_ACCOUNT_LISTS_FAIL';